import {LEVELS,WEAPONS,MODULES,DEFAULT_OPTIONS,SAVE_KEY,OPTIONS_KEY,freshCampaign,sanitizeSave,sanitizeOptions,readStored,writeStored,highestUnlocked,unlockedWeapon,upgradeCost,buyUpgrade,weaponStats,awardMission} from './campaign.js';
const el=id=>document.getElementById(id);
export function mountCampaign(api){
 let storage;try{storage=localStorage;}catch{storage={getItem(){throw Error('Storage unavailable');},setItem(){throw Error('Storage unavailable');}};}
 const loaded=readStored(storage,SAVE_KEY,sanitizeSave),prefs=readStored(storage,OPTIONS_KEY,sanitizeOptions);
 let save=loaded.value,options=sanitizeOptions(prefs.value||{}),returnFocus=null,resumeAfter=null,currentPanel='',pendingMission=0,busy=false,pendingConfirm=null;
 let warning=loaded.error?'Save unavailable or damaged. Existing data has not been overwritten.':prefs.error?'Options could not be loaded; using defaults.':'';
 const panel=el('campaign-panel'),body=el('panel-body');
 function persist(){if(!save)return;if(!writeStored(storage,SAVE_KEY,save))warning='Storage unavailable. Progress is kept only for this session.';refresh();}
 function persistOptions(){if(!writeStored(storage,OPTIONS_KEY,options))warning='Options could not be saved on this device.';api.options(options);refresh();}
 function refresh(){el('save-status').textContent=warning||(save?`CAMPAIGN ${highestUnlocked(save)} / 5 · ${save.credits} SCRAP`:'NO ACTIVE CAMPAIGN');el('continue').textContent=save?`CONTINUE · ${String(highestUnlocked(save)).padStart(2,'0')}`:'CONTINUE';el('campaign-wallet').textContent=`${save?.credits||0} SCRAP`;el('storage-warning').textContent=warning;}
 function close(resume=true){if(!panel.open)return;pendingConfirm=null;api.preview(false);panel.close();if(resume)resumeAfter?.();resumeAfter=null;returnFocus?.focus();}
 function show(title,html,type){if(!panel.open){returnFocus=document.activeElement;resumeAfter=api.suspend();panel.showModal();}currentPanel=type;panel.dataset.panel=type;api.preview(type==='hangar');el('panel-title').textContent=title;body.innerHTML=html;el('panel-close').focus();refresh();}
 function title(){close(false);api.title();refresh();}
 function confirmAction(message,accept,cancel=()=>close()){pendingConfirm={accept,cancel};show('CONFIRM ACTION',`<p>${message}</p><div class="panel-actions"><button data-confirm-cancel>KEEP CURRENT PROGRESS</button><button class="danger" data-confirm-accept>CONFIRM</button></div>`,'confirm');body.querySelector('[data-confirm-cancel]').focus();}
 function newGame(){const begin=()=>{save=freshCampaign();warning='';persist();briefing(1);};if(save||loaded.error){confirmAction('Start a new campaign? This replaces your mission records, scrap, weapons and upgrades. Graphics and controls are kept.',begin);return;}begin();}
 function briefing(id){if(!save||id>highestUnlocked(save))return;pendingMission=id;const l=LEVELS[id-1];show('MISSION BRIEFING',`<div class="brief-number">${String(l.id).padStart(2,'0')} <span>/ 05</span></div><p class="panel-kicker">${l.subtitle}</p><h3 class="mission-title">${l.title}</h3><p>${l.briefing}</p><div class="brief-stats"><span>DIFFICULTY <b>${'◆'.repeat(l.difficulty)}</b></span><span>PAR TIME <b>${l.parTime}s</b></span><span>FIRST CLEAR <b>${l.rewards.scrap} SCRAP + RATING BONUS</b></span></div><p class="panel-note">${l.enemyWaves.length} hostile frame${l.enemyWaves.length>1?'s':''} · ${WEAPONS[save.equipped].name} Mk ${save.upgrades[save.equipped]+1} · ${MODULES[save.module].name}</p><button class="primary" data-launch="${id}">DEPLOY FRAME <span>↗</span></button><button class="text-button" data-panel="hangar">ADJUST LOADOUT</button>`,'briefing');}
 function levels(){show('LEVEL SELECT',`<p class="panel-note">Five platforms. One orbit. Complete each mission to unlock the next. Replays earn 35% base scrap plus a rating bonus.</p><div class="level-list">${LEVELS.map(l=>{const r=save?.completed[l.id],locked=!save||l.id>highestUnlocked(save);return `<button class="level-row ${locked?'locked':''}" data-brief="${l.id}" ${locked?'disabled':''}><span class="level-number">0${l.id}</span><span><small>${l.subtitle}</small><strong>${l.title}</strong><em>${locked?'LOCKED':r?'COMPLETED · REPLAY':'UNLOCKED'} · DIFFICULTY ${l.difficulty}/5</em><small>BEST ${r?r.score.toLocaleString():'—'} · RATING ${r?.rating||'—'} · TIME ${r?formatTime(r.time):'—'}</small></span><span class="level-rating">${r?.rating||(locked?'×':'↗')}</span></button>`;}).join('')}</div>${save?'':'<p>Start a New Game to activate the campaign.</p>'}`,'levels');}
 function hangar(){api.previewLoadout(save);const stats=weaponStats(save);show('HANGAR / LOADOUT',`<p class="panel-note">VX–09 VEILWALKER · Configure your frame for the next deployment. Upgrades add 20% base damage per rank, up to Mk IV.</p><div class="weapon-list">${Object.entries(WEAPONS).map(([id,w])=>{const unlocked=unlockedWeapon(save,id),rank=save?.upgrades[id]||0,cost=upgradeCost(rank),dmg=w.damage*(1+rank*.2);return `<article class="loadout-row ${save?.equipped===id?'equipped':''}"><small>${unlocked?'AVAILABLE':`UNLOCK: COMPLETE LEVEL ${w.unlock}`}</small><h3>${w.name} <span>Mk ${rank+1}</span></h3><p>${w.description}</p><div class="weapon-stats">DAMAGE <b>${dmg.toFixed(1)}${rank<3?` → ${(dmg+w.damage*.2).toFixed(1)}`:''}</b> · RATE <b>${(1/w.interval).toFixed(1)}/s</b> · HEAT <b>${w.heat}</b></div><button data-equip="${id}" ${!save||!unlocked||save.equipped===id?'disabled':''}>${save?.equipped===id?'EQUIPPED':'EQUIP'}</button><button data-upgrade="${id}" ${!save||!unlocked||rank>=3||save.credits<cost?'disabled':''}>${rank>=3?'MAX UPGRADE':`UPGRADE · ${cost} SCRAP`}</button></article>`;}).join('')}</div><h3>CORE MODULE</h3><div class="module-list">${Object.entries(MODULES).map(([id,m])=>`<button data-module="${id}" ${!save||(id!=='balanced'&&!save.completed[2])?'disabled':''} aria-pressed="${save?.module===id}"><b>${m.name}</b><span>${m.description}</span>${id!=='balanced'&&!save?.completed[2]?'<small>COMPLETE LEVEL 2</small>':''}</button>`).join('')}</div><p class="panel-note">Equipped output: ${(stats.damage/stats.interval).toFixed(1)} damage/s before armor. ${save?'Changes save immediately and apply on your next deployment.':'Start a New Game to equip and upgrade.'}</p>${pendingMission&&save?`<button class="primary" data-brief="${pendingMission}">BACK TO BRIEFING <span>↗</span></button>`:''}`,'hangar');}
 const select=(key,label,choices)=>`<label class="option"><span>${label}</span><select data-option="${key}">${choices.map(([v,t])=>`<option value="${v}" ${options[key]===v?'selected':''}>${t}</option>`).join('')}</select></label>`;
 const check=(key,label)=>`<label class="option"><span>${label}</span><input type="checkbox" data-option="${key}" ${options[key]?'checked':''}></label>`;
 function settings(){show('OPTIONS',`<div class="options-grid">${select('quality','Graphics quality',[['high','High'],['medium','Medium']])}${select('shadows','Shadow quality',[['high','High · 2048'],['medium','Medium · 1024'],['off','Off']])}${check('bloom','Bloom')}${select('particles','Particle density',[['high','High'],['medium','Medium']])}${check('shake','Screen shake')}${check('reducedMotion','Reduced motion')}${check('mute','Mute')}<label class="option"><span>Audio volume</span><input type="range" min="0" max="1" step=".05" value="${options.volume}" data-option="volume"></label><label class="option"><span>Mouse / stick sensitivity</span><input type="range" min=".3" max="2.5" step=".1" value="${options.sensitivity}" data-option="sensitivity"></label>${check('aimAssist','Aim assist (manual mode)')}${check('invertY','Invert vertical aim')}${select('controlMode','Control mode',[['assisted','Assisted · auto target'],['manual','Manual · aim reticle']])}</div><p class="panel-note">Manual: move the mouse, right stick, or drag on the arena to aim. Assisted retains the original automatic targeting. Reduced motion disables shake, impact slowdown and camera orbits.</p><div class="panel-actions"><button data-defaults>RESTORE DEFAULTS</button><button class="danger" data-reset>RESET PROGRESS</button></div>`,'options');}
 function controls(){close();api.controls();}
 function continueGame(){if(!save){show('NO ACTIVE CAMPAIGN','<p>Select New Game to begin your first deployment.</p><button class="primary" data-new>NEW GAME <span>↗</span></button>','empty');return;}briefing(highestUnlocked(save));}
 function open(name){({levels,hangar,options:settings,controls})[name]?.();}
 el('deploy').onclick=newGame;el('continue').onclick=continueGame;
 document.querySelectorAll('[data-open-panel]').forEach(b=>b.onclick=()=>open(b.dataset.openPanel));
 document.querySelectorAll('[data-title]').forEach(b=>b.onclick=()=>{if(api.inCombat()){confirmAction('Return to title? The current attempt will be abandoned. Earned campaign progress is kept.',title);return;}title();});
 el('panel-close').onclick=()=>close();panel.addEventListener('cancel',e=>{e.preventDefault();close();});
 body.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
  if(b.hasAttribute('data-new'))newGame();
  if(b.hasAttribute('data-confirm-cancel')&&pendingConfirm){const cancel=pendingConfirm.cancel;pendingConfirm=null;cancel();}
  if(b.hasAttribute('data-confirm-accept')&&pendingConfirm){const accept=pendingConfirm.accept;pendingConfirm=null;accept();}
  if(b.dataset.panel)open(b.dataset.panel);
  if(b.dataset.brief)briefing(Number(b.dataset.brief));
  if(b.dataset.launch&&!busy){busy=true;b.disabled=true;b.textContent='PREPARING PLATFORM…';try{await api.load(Number(b.dataset.launch));if(!panel.open||currentPanel!=='briefing'||Number(b.dataset.launch)!==pendingMission||!save)return;close(false);api.launch(Number(b.dataset.launch),save);}catch(err){warning='Mission could not load. Please try again.';refresh();b.textContent='RETRY DEPLOYMENT';}finally{busy=false;b.disabled=false;}}
  if(b.dataset.equip&&save&&unlockedWeapon(save,b.dataset.equip)){save.equipped=b.dataset.equip;persist();hangar();}
  if(b.dataset.upgrade&&buyUpgrade(save,b.dataset.upgrade)){persist();hangar();}
  if(b.dataset.module&&save&&(b.dataset.module==='balanced'||save.completed[2])){save.module=b.dataset.module;persist();hangar();}
  if(b.hasAttribute('data-defaults')){options={...DEFAULT_OPTIONS};persistOptions();settings();}
  if(b.hasAttribute('data-reset'))confirmAction('Permanently reset campaign progress, scrap, weapons and ratings? This cannot be undone. Graphics and controls are kept.',()=>{try{storage.removeItem(SAVE_KEY);save=null;warning='';title();}catch{warning='Reset failed. Your progress was kept.';settings();}},settings);
 });
 body.addEventListener('change',e=>{const k=e.target.dataset.option;if(!k)return;options=sanitizeOptions({...options,[k]:e.target.type==='checkbox'?e.target.checked:e.target.type==='range'?Number(e.target.value):e.target.value});persistOptions();});
 refresh();api.options(options);
 return {get save(){return save;},get options(){return options;},open,briefing,title,refresh,
  option(key,value){options=sanitizeOptions({...options,[key]:value});persistOptions();},
  reward(level,time,hull,run){const r=awardMission(save,level,time,hull,run);if(r)persist();return r;},
  close:()=>close(false)};
}
export function formatTime(seconds){return `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;}


