import * as THREE from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {LEVELS,WEAPONS,MODULES,DEFAULT_OPTIONS,weaponStats,strikeOffsets} from './campaign.js';
import {mountCampaign,formatTime} from './campaign-ui.js';
import {createInput} from './input.js';
import {LightPool, ImpactPool, makeSurfaceMaps} from './systems.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const uiCache=new Map();const $=s=>{if(!uiCache.has(s))uiCache.set(s,document.querySelector(s));return uiCache.get(s);}, canvas=$('#world');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<800?1.25:1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color('#101f2d');scene.fog=new THREE.FogExp2('#172b3b',.014);
const pmrem=new THREE.PMREMGenerator(renderer), studio=new RoomEnvironment();
const environment=pmrem.fromScene(studio,.06);scene.environment=environment.texture;scene.environmentIntensity=.55;studio.dispose();pmrem.dispose();
const camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,450);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloomPass=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.32,.6,1.1);composer.addPass(bloomPass);composer.addPass(new OutputPass());
let seed=32;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
function texture(base,mark=false){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.fillStyle=base;x.fillRect(0,0,512,512);for(let i=0;i<5500;i++){let v=rand()*255;x.fillStyle=`rgba(${v},${v},${v},${rand()*.1})`;x.fillRect(rand()*512,rand()*512,rand()*10,1)}x.strokeStyle='#101b2455';x.lineWidth=3;x.strokeRect(18,18,476,476);x.strokeRect(29,30,455,452);for(let i=0;i<140;i++){x.strokeStyle=rand()>.5?'#e2e7e333':'#0a172855';let a=rand()*512,b=rand()*512;x.beginPath();x.moveTo(a,b);x.lineTo(a+rand()*26,b+rand()*3);x.stroke()}if(mark){x.fillStyle='#18272d';x.font='bold 56px monospace';x.fillText('09',58,130);x.font='12px monospace';x.fillText('VX / VEILWALKER',58,154);x.fillStyle='#c88443';x.fillRect(365,48,48,8);x.fillStyle='#283740';for(let i=0;i<10;i++)x.fillRect(60+i*7,430,3,25);x.font='10px monospace';x.fillText('CAUTION / ION DRIVE',58,407)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
const tex=texture('#b8c0bc',true), darktex=texture('#303d45'),groundtex=texture('#34434a');groundtex.wrapS=groundtex.wrapT=THREE.RepeatWrapping;groundtex.repeat.set(14,14);
const mat=(color,metalness=.6,roughness=.35,map=null)=>new THREE.MeshStandardMaterial({color,metalness,roughness,map});
const ivory=mat('#d5d8cf',.65,.32,tex), graphite=mat('#29353e',.8,.32,darktex),steel=mat('#768c99',.9,.24),black=mat('#111a22',.35,.65),copper=mat('#a56942',.75,.34),bossmat=mat('#474653',.8,.32,darktex);
const surface=makeSurfaceMaps();
for(const m of [ivory,graphite,steel,copper,bossmat]){m.roughnessMap=surface;m.bumpMap=surface;m.bumpScale=.022;}
ivory.metalness=.35;ivory.roughness=.55;bossmat.color.set('#858090');graphite.color.set('#66747d');
const ceramic=new THREE.MeshPhysicalMaterial({color:'#c6d3d1',metalness:.3,roughness:.31,clearcoat:.35,clearcoatRoughness:.3,roughnessMap:surface});
const carbon=new THREE.MeshStandardMaterial({color:'#26333c',roughness:.55,metalness:.3,map:surface});
const glow=c=>new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:1.8,metalness:.3,roughness:.25});const cyan=glow('#79eeef'),amber=glow('#e98e42'),purple=glow('#b984ff'),red=glow('#ff4242');
const boxcache=new Map();function block(parent,w,h,d,x,y,z,m=graphite,r=.08){let key=[w,h,d,r].join();let geo=boxcache.get(key);if(!geo){geo=new RoundedBoxGeometry(w,h,d,2,r);boxcache.set(key,geo)}let o=new THREE.Mesh(geo,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function plate(parent,w,h,d,x,y,z,m,tilt=0){const shape=new THREE.Shape();shape.moveTo(-w*.5,-h*.32);shape.lineTo(-w*.34,-h*.5);shape.lineTo(w*.3,-h*.5);shape.lineTo(w*.5,-h*.22);shape.lineTo(w*.45,h*.35);shape.lineTo(w*.2,h*.5);shape.lineTo(-w*.4,h*.45);shape.closePath();let g=new THREE.ExtrudeGeometry(shape,{depth:d,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.055,bevelThickness:.045,curveSegments:8});g.center();let o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.rotation.z=tilt;o.castShadow=true;parent.add(o);return o}
function tube(parent,a,b,r,m){let curve=new THREE.CatmullRomCurve3(a.map(p=>new THREE.Vector3(...p)));let o=new THREE.Mesh(new THREE.TubeGeometry(curve,b,r,8,false),m);parent.add(o);return o}
function ring(parent,r,t,x,y,z,m){let o=new THREE.Mesh(new THREE.TorusGeometry(r,t,10,40),m);o.position.set(x,y,z);parent.add(o);return o}
function mech(boss=false){const g=new THREE.Group(), armor=boss?bossmat:ivory,energy=boss?purple:cyan;const legs=[],arms=[];block(g,1.55,.65,.85,0,2.15,0,graphite);plate(g,2.1,1.55,1.05,0,3.28,0,armor);plate(g,1.65,.65,.23,0,3.65,.66,graphite);plate(g,.85,.7,.15,0,3.2,.72,steel);ring(g,.26,.075,0,3.28,.86,steel);ring(g,.18,.055,0,3.28,.89,energy);block(g,.24,.23,.08,0,3.28,.91,energy);
for(let s of [-1,1]){for(let i=0;i<4;i++)block(g,.35,.055,.13,s*.65,2.83+i*.1,.69,black,.02);const leg=new THREE.Group();leg.position.set(s*.58,2.15,0);g.add(leg);legs.push(leg);block(leg,.47,.72,.47,0,-.4,0,black);plate(leg,.76,.85,.6,0,-.55,.12,armor,s*.1);ring(leg,.24,.09,0,-1,.36,steel);plate(leg,.65,.45,.23,0,-1,.48,graphite);block(leg,.39,.8,.45,0,-1.5,0,steel);plate(leg,.77,.9,.55,s*.06,-1.53,.25,armor);block(leg,.83,.32,1.28,0,-2.03,.3,graphite);plate(leg,.78,.22,.5,0,-1.95,.85,armor);block(leg,.035,.48,.04,s*.21,-1.4,.57,energy,.01);tube(leg,[[s*.25,-.7,-.3],[s*.37,-1.1,-.42],[s*.27,-1.8,-.2]],12,.05,copper);
const arm=new THREE.Group();arm.position.set(s*1.25,3.75,0);g.add(arm);arms.push(arm);block(arm,.5,.65,.65,0,-.2,0,black);plate(arm,1.0,.76,.92,s*.15,0,.04,armor,-s*.16);plate(arm,.88,.45,.2,s*.15,.15,.63,graphite);block(arm,.42,.72,.43,s*.14,-.75,0,steel);plate(arm,.6,.72,.58,s*.14,-.65,.1,armor);ring(arm,.2,.08,s*.13,-1.05,.33,steel);plate(arm,.73,.93,.72,s*.17,-1.5,.1,armor,-s*.08);block(arm,.4,.26,.4,s*.17,-2,.13,black);tube(arm,[[0,-.4,-.35],[s*.3,-1,-.5],[s*.23,-1.65,-.23]],16,.06,black);for(let i=0;i<4;i++)block(arm,.38,.035,.05,s*.17,-1.32-i*.12,.51,steel,.01);
block(g,.46,1.5,.65,s*.75,3.05,-.82,graphite);plate(g,.5,1.4,.25,s*.75,3.1,-1.15,armor);ring(g,.18,.06,s*.75,2.5,-1.3,energy);for(let i=0;i<5;i++)block(g,.4,.045,.09,s*.75,3+i*.12,-1.31,black,.01);tube(g,[[s*.65,3.8,-.55],[s*1.1,3.3,-.8],[s*.8,2.3,-.5]],20,.055,copper);
}block(g,.35,.3,.35,0,4.2,0,steel);plate(g,.75,.65,.66,0,4.55,.07,armor);plate(g,.68,.19,.15,0,4.55,.48,black);block(g,.52,.05,.08,0,4.57,.58,energy,.015);plate(g,.23,.5,.15,0,4.35,.5,graphite);block(g,.055,.65,.055,-.32,4.95,-.07,steel,.015);
const gun=new THREE.Group();gun.position.set(1.47,1.8,.6);g.add(gun);plate(gun,.62,.68,1.55,0,.13,.62,graphite);block(gun,.32,.31,1.7,0,.22,1.4,steel);block(gun,.48,.48,.38,0,.22,2.2,graphite);block(gun,.21,.2,.02,0,.22,2.41,energy);block(gun,.07,.09,1.2,.32,.3,1.1,energy);for(let i=0;i<5;i++)block(gun,.65,.09,.1,0,.5,.3+i*.21,black,.025);
if(boss){g.scale.setScalar(1.75);for(let s of [-1,1]){plate(g,1.6,1.5,1.4,s*1.55,4,.0,bossmat,s*.18);for(let i=0;i<3;i++){block(g,.3,.3,2.7,s*(1.3+i*.3),4.5,.75,graphite);ring(g,.1,.04,s*(1.3+i*.3),4.5,2.15,purple)}plate(g,.65,2.3,.4,s*.65,4.7,-.65,bossmat,-s*.35)}ring(g,.56,.08,0,3.3,.9,purple);ring(g,.74,.04,0,3.3,.9,steel)}g.userData={legs,arms,gun};scene.add(g);return g}
const hero=mech(),boss=mech(true);
const baseBossParts=new Set(boss.children);
// Acheron's siege mantle and radial reactor distinguish its silhouette.
for(const s of [-1,1]) { const mantle=plate(boss,1.3,3.1,.55,s*2.05,3.25,-.3,bossmat,-s*.3); plate(boss,1.05,2.6,.15,s*2.08,3.3,.08,graphite,-s*.3); for(let j=0;j<5;j++)block(boss,.55,.08,.12,s*2.12,2.7+j*.24,.23,j===2?purple:steel,.015); tube(boss,[[s*.5,3.3,.8],[s*1.2,2.8,.65],[s*1.9,3.4,.25]],24,.075,copper); plate(boss,.55,1.45,.5,s*.47,4.9,.05,graphite,-s*.25); }
for(let j=0;j<8;j++){let a=j*Math.PI/4;const fin=plate(boss,.18,.52,.12,Math.sin(a)*.77,3.3+Math.cos(a)*.77,1,steel,-a);}
boss.userData.siegeAttachments=boss.children.filter(part=>!baseBossParts.has(part));
// Additional armor leaves and layered dorsal heat exchanger.
for(const side of [-1,1]){
  plate(hero,.7,1.05,.18,side*.65,3.4,-.64,ceramic,side*.2);
  plate(hero,.46,.85,.14,side*.56,2.08,-.49,carbon,-side*.14);
  for(let j=0;j<6;j++)block(hero,.43,.04,.13,side*.65,3.06+j*.12,-.81,steel,.015);
  tube(hero,[[side*.35,3.7,-.75],[side*.45,3.2,-.94],[side*.3,2.5,-.63]],20,.035,copper);
  const shoulder=hero.userData.arms[side===-1?0:1];
  plate(shoulder,.75,.63,.16,side*.2,.09,-.55,ceramic,-side*.2);
}
hero.position.set(0,0,5);boss.position.set(0,0,-19);boss.rotation.y=0;
scene.add(new THREE.HemisphereLight('#b4d8ed','#1b2630',2.1));function light(color,intensity,pos,target){const l=new THREE.DirectionalLight(color,intensity);l.position.set(...pos);if(target)l.target.position.set(...target);scene.add(l,l.target);return l}const key=light('#bfdeed',3.8,[-12,25,12]);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-34,right:34,top:36,bottom:-36,near:1,far:95});key.shadow.bias=-.0003;light('#599aaa',3,[15,10,-15]);light('#ecaa77',2,[-20,8,-2]);const lightPool=new LightPool(scene,3);
block(scene,58,.65,64,0,-.52,-9,mat('#65747a',.78,.29,groundtex),.15);
const hazardMat=mat('#bd9c65',.4,.6);
const lineMat=mat('#9caa9a',.5,.38);for(let x=-27;x<=27;x+=6){for(let z=-36;z<23;z+=6){block(scene,5.95,.025,.022,x,-.177,z,black,.005);block(scene,.025,.025,5.95,x,-.177,z,black,.005)}}
for(let s of [-1,1]){for(let z=-37;z<25;z+=4){block(scene,.12,.03,2.8,s*20,-.15,z,lineMat,.01);block(scene,1.1,.3,2,s*27,0,z,graphite);block(scene,.08,.04,1.3,s*25.5,-.1,z,cyan,.01)}for(let z of [-28,-10,9]){block(scene,3,1.1,2,s*23,.4,z,graphite);plate(scene,2.7,.8,.12,s*23,.65,z+1,steel);block(scene,1.8,.09,.04,s*23,.9,z+1.08,amber);for(let i=0;i<6;i++)block(scene,.2,.65,.1,s*23-1+i*.4,.55,z+1.1,black,.015)}for(let z=-35;z<25;z+=7){block(scene,.16,1.2,.16,s*28,.35,z,steel);block(scene,.12,.12,7,s*28,.9,z+3.5,steel)}}
// Authored landing markings and concentric reactor pad.
for(let r of [8,8.25,10.4]){const o=ring(scene,r,.035,0,-.13,-17,r===8.25?cyan:lineMat);o.rotation.x=-Math.PI/2}
for(let s of [-1,1])for(let z=-30;z<20;z+=2){let o=block(scene,1.1,.03,.18,s*12,-.12,z,hazardMat,.01);o.rotation.y=s*.6}
function sign(text,color,w,h){const c=document.createElement('canvas');c.width=1024;c.height=256;let x=c.getContext('2d');x.fillStyle='#08151c';x.fillRect(0,0,1024,256);x.strokeStyle=color;x.lineWidth=5;x.strokeRect(10,10,1004,236);x.fillStyle=color;x.font='bold 92px monospace';x.fillText(text,50,150);x.font='24px monospace';x.fillText('HELIX TRANSIT AUTHORITY  //  SECTOR 07',55,210);let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshStandardMaterial({map:t,emissiveMap:t,emissive:'#ffffff',emissiveIntensity:1.2,transparent:true}))}
const evac=sign('EVACUATE →','#edb785',13,3.25);evac.position.set(-22,6,-29);scene.add(evac);block(scene,.3,7,.3,-28,2.5,-29,steel);block(scene,.3,7,.3,-16,2.5,-29,steel);
// Skyline: tiered towers, skybridges and the orbital tether.
const cityMetal=mat('#243846',.65,.48),windowMetal=mat('#56838d',.6,.4);
for(let i=0;i<46;i++){let x=(rand()-.5)*220,z=-45-rand()*110;if(Math.abs(x)<15)x+=28;let h=18+rand()*80,w=5+rand()*12;block(scene,w,h,6+rand()*10,x,h/2-9,z,cityMetal);block(scene,w*.7,h*.3,7,x,h-10,z,graphite);for(let row=0;row<Math.floor(h/4);row++){block(scene,w*.75,.08,.05,x,row*4-1,z+6,rand()>.85?amber:windowMetal);}if(i%4===0){block(scene,.08,h+10,.08,x,h/2,z,cyan,.02);const ad=sign(i%8===0?'未来 / HELIX':'NO SIGNAL',i%8===0?'#79c4d0':'#c895a9',w*.75,w*.19);ad.position.set(x,h*.65,z+7);scene.add(ad)}}
block(scene,8,180,9,5,60,-140,graphite);block(scene,.4,240,.4,5,100,-134,cyan);for(let y=10;y<110;y+=16){block(scene,22,1,12,5,y,-140,steel)}block(scene,63,2.4,6,-43,14,-58,graphite);block(scene,32,1.5,4,39,22,-78,graphite);
// Rain: one pooled line geometry.
let rainPos=new Float32Array(1800*6);for(let i=0;i<1800;i++){let k=i*6,x=(rand()-.5)*100,y=rand()*50,z=(rand()-.5)*100;rainPos.set([x,y,z,x-.13,y+.7,z],k)}let rainGeo=new THREE.BufferGeometry();rainGeo.setAttribute('position',new THREE.BufferAttribute(rainPos,3));scene.add(new THREE.LineSegments(rainGeo,new THREE.LineBasicMaterial({color:'#99b8c5',transparent:true,opacity:.18,depthWrite:false})));
// Ground glints approximate elongated neon reflections without a costly reflection pass.
const puddleMat=new THREE.MeshBasicMaterial({color:'#58a5b5',transparent:true,opacity:.07,depthWrite:false});for(let i=0;i<60;i++){let p=new THREE.Mesh(new THREE.PlaneGeometry(.1+rand()*.5,1+rand()*6),puddleMat);p.rotation.x=-Math.PI/2;p.position.set((rand()-.5)*50,-.155,(rand()-.5)*55-7);scene.add(p)}
// Batch stationary architecture by material to reduce draw calls.
const batches=new Map();scene.updateMatrixWorld(true);for(const o of [...scene.children]){if(o.isMesh){const id=o.material.uuid;if(!batches.has(id))batches.set(id,{mat:o.material,geos:[]});batches.get(id).geos.push((o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone()).applyMatrix4(o.matrixWorld));scene.remove(o);}}for(const b of batches.values()){const merged=mergeGeometries(b.geos,false);if(merged){const m=new THREE.Mesh(merged,b.mat);m.receiveShadow=true;scene.add(m);for(const geo of b.geos)geo.dispose();}else for(const geo of b.geos)scene.add(new THREE.Mesh(geo,b.mat));}batches.clear();const liveGeometry=new Set();scene.traverse(o=>{if(o.geometry)liveGeometry.add(o.geometry);});for(const [id,geo] of boxcache){if(!liveGeometry.has(geo)){geo.dispose();boxcache.delete(id);}}
const warning=new THREE.Mesh(new THREE.RingGeometry(3.8,4,64),new THREE.MeshBasicMaterial({color:'#ff694d',transparent:true,opacity:.8,side:THREE.DoubleSide}));warning.rotation.x=-Math.PI/2;warning.position.y=.02;warning.visible=false;scene.add(warning);
const impacts=new ImpactPool(scene);let settings={...DEFAULT_OPTIONS};function burst(pos,color,n=25,power=6){impacts.emit(pos,color,Math.ceil(n*(settings.particles==='medium'?.45:1)),power);}
const shock=new THREE.Mesh(new THREE.RingGeometry(.95,1,96),new THREE.MeshBasicMaterial({color:'#ffd3a0',transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false}));shock.rotation.x=-Math.PI/2;scene.add(shock);let shockAge=9,hitStop=0;
function impact(pos,color,power=45){lightPool.emit(pos,color,power,.35,camera,2);shock.position.copy(pos);shock.position.y=.05;shockAge=0;}
const beam=new THREE.Mesh(new THREE.CylinderGeometry(.035,.08,1,8),cyan);beam.visible=false;scene.add(beam);let beamLife=0;function tracer(a,b,color){beam.material=color;beam.position.copy(a).add(b).multiplyScalar(.5);beam.scale.y=a.distanceTo(b);beam.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());beam.visible=true;beamLife=.06}
// The existing state loop now takes its encounter parameters from the campaign.
let mode='menu',returnMode='play',hp=100,maxHp=100,bhp=100,maxBhp=100,heat=0,elapsed=0,attackTimer=4,telegraph=0,phase=1,shot=0,dash=0,qcd=0,shake=0,noticeT=0,overheat=false,fire=false,intro=0,victory=0,walk=0,deathPulse=0;
let level=LEVELS[0],waveIndex=0,enemy=level.enemyWaves[0],weapon={...WEAPONS.arc},moduleStats=MODULES.balanced,runId='',loadoutRank=0,result=null,campaign,input,missionSet;
let hangarPreview=false;let audio,guidePausedGame=false,guideFocus=null,steamTimer=0,uiTimer=0;
const keys=new Set(),aimPoint=new THREE.Vector3(),muzzlePoint=new THREE.Vector3(),enemyPoint=new THREE.Vector3();
const targetCam=new THREE.Vector3(),look=new THREE.Vector3();camera.position.set(11,6.2,16);
const warningMarkers=[warning];for(let i=1;i<5;i++){const m=new THREE.Mesh(warning.geometry,warning.material);m.rotation.copy(warning.rotation);m.visible=false;m.position.y=.02;scene.add(m);warningMarkers.push(m);}
const strikePositions=Array.from({length:5},()=>new THREE.Vector3());let strikeCount=0,strikeRadius=4;
function tone(freq,dur=.12,type='sawtooth',vol=.025){if(settings.mute||settings.volume<=0||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.3,audio.currentTime+dur);g.gain.setValueAtTime(Math.max(.001,vol*settings.volume),audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur);o.onended=()=>{o.disconnect();g.disconnect();};}
function activateAudio(){try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});}catch{}}
function notice(text){$('#notice').textContent=text;noticeT=3;}
function clearStrikes(){telegraph=0;strikeCount=0;warningMarkers.forEach(m=>m.visible=false);}
function previewLoadout(save){if(!['play','intro','waveDefeat','victory','pause'].includes(mode))weapon=weaponStats(save);hero.userData.gun.scale.set(save?.equipped==='lance'?1.15:1,1,save?.equipped==='lance'?1.22:save?.equipped==='pulse'?.82:1);$('.weapon>small').textContent=weapon.name.toUpperCase();$('#frame-primary').textContent=weaponStats(save).name.toUpperCase()+' / MK. '+((save?.upgrades[save.equipped]||0)+1);}
function spawnEnemy(){enemy=level.enemyWaves[waveIndex];bhp=maxBhp=enemy.health;phase=1;attackTimer=3;clearStrikes();boss.visible=true;boss.position.set(0,0,-19);boss.rotation.set(0,0,0);boss.scale.setScalar(enemy.scale);boss.userData.siegeAttachments.forEach(part=>part.visible=level.id>=4||(level.id===3&&waveIndex>0));boss.userData.arms.forEach(a=>a.rotation.set(0,0,0));purple.color.set(level.color);purple.emissive.set(level.color);purple.emissiveIntensity=1.8;$('#enemy-name').textContent=enemy.name;$('#phase').textContent='01 / ARMORED';$('.objective>span').textContent=`HOSTILE ${waveIndex+1} / ${level.enemyWaves.length}`;$('.boss').hidden=false;}
async function loadMission(id){if(!missionSet){const {createMissionSet}=await import('./mission-scene.js');missionSet=createMissionSet(scene);}}
function start(id=level.id,save=campaign?.save){if(!save)return;level=LEVELS[id-1];if(!level)return;missionSet?.apply(level);document.body.classList.remove('is-paused');document.body.classList.add('playing');document.body.dataset.mode='intro';moduleStats=MODULES[save.module];maxHp=moduleStats.hull;hp=maxHp;heat=0;overheat=fire=false;dash=shot=elapsed=qcd=walk=0;waveIndex=0;result=null;runId=crypto.randomUUID();lightPool.clear();impacts.clear();hitStop=0;shockAge=9;beamLife=0;keys.clear();input?.clear();hero.position.set(0,0,7);hero.rotation.set(0,Math.PI,0);hero.userData.legs.forEach(l=>l.rotation.x=0);weapon=weaponStats(save);loadoutRank=save.upgrades[save.equipped];previewLoadout(save);spawnEnemy();scene.background.set(level.sky);scene.fog.color.set(level.sky);scene.fog.density=level.id===4?.019:.013;key.color.set(level.id===2?'#f0c4a2':'#bfdeed');cityMetal.color.set(level.id===2?'#493839':'#243846');mode='intro';intro=settings.reducedMotion?.6:2.5;$('#hud').hidden=false;$('#overlay').hidden=true;$('#reticle').hidden=false;$('#next-mission').hidden=true;$('.objective strong').textContent=level.objectives[0].text;$('.objective small').textContent=`0${level.id} / ${level.title.toUpperCase()}`;$('#footerlabel').textContent=level.subtitle;notice('HOSTILE SIGNATURE / '+enemy.name);activateAudio();}
function returnTitle(){mode='menu';document.body.classList.remove('playing','is-paused','damage');document.body.dataset.mode='menu';$('#hud').hidden=true;$('#overlay').hidden=true;$('#next-mission').hidden=true;clearStrikes();fire=false;keys.clear();input?.clear();impacts.clear();lightPool.clear();shockAge=9;beamLife=0;boss.visible=false;missionSet?.hide();hero.position.set(0,0,5);hero.userData.legs.forEach(l=>l.rotation.x=0);scene.background.set('#101f2d');scene.fog.color.set('#172b3b');key.color.set('#bfdeed');scene.fog.density=.014;$('#footerlabel').textContent='ORBITAL COMMAND / AWAITING PILOT';notice('');campaign?.refresh();}
function pause(){if(['play','victory','waveDefeat','intro'].includes(mode)){returnMode=mode;mode='pause';document.body.classList.add('is-paused');document.body.dataset.mode='pause';fire=false;keys.clear();input?.clear();$('#overlay').hidden=false;$('#overlabel').textContent='UPLINK SUSPENDED';$('#overtitle').textContent='SYSTEM PAUSED';$('#overtext').textContent='Your campaign progress is safe. This attempt resumes here.';$('#resume').innerHTML='RESUME OPERATION <span>↗</span>';}else if(mode==='pause'){mode=returnMode;document.body.classList.remove('is-paused');document.body.dataset.mode=mode;$('#overlay').hidden=true;}}
function suspend(){if(['play','intro','victory','waveDefeat'].includes(mode)){pause();return ()=>{if(mode==='pause')pause();};}return null;}
function openGuide(){if($('#guide').open||$('#campaign-panel').open)return;guideFocus=document.activeElement;guidePausedGame=!!suspend();keys.clear();fire=false;$('#guide').showModal();$('#close-help').focus();}
function closeGuide(){if(!$('#guide').open)return;$('#guide').close();if(guidePausedGame&&mode==='pause')pause();guidePausedGame=false;guideFocus?.focus();}
function action(code){if($('#guide').open||$('#campaign-panel').open)return;if(code==='KeyH'){openGuide();return;}if(code==='Escape'){pause();return;}if(mode!=='play')return;
 if(code==='Space'&&dash<=0){dash=.7;burst(hero.position.clone().add(new THREE.Vector3(0,.5,0)),'#79eeef',30,4);tone(150,.3);}
 if(code==='KeyQ'&&qcd<=0){qcd=12;bhp=Math.max(0,bhp-22*(1+loadoutRank*.15));shake=.4;hitStop=.07;impact(boss.position,level.color,100);burst(boss.position.clone().add(new THREE.Vector3(0,5,0)),level.color,70,15);tracer(hero.position.clone().add(new THREE.Vector3(0,3,0)),boss.position.clone().add(new THREE.Vector3(0,5,0)),purple);tone(70,.6);notice('OVERDRIVE / CORE DISCHARGE');}
}
addEventListener('keydown',e=>{if($('#guide').open||$('#campaign-panel').open)return;if(['Space','ArrowUp','ArrowDown'].includes(e.code)&&mode==='play')e.preventDefault();keys.add(e.code);if(!e.repeat)action(e.code);});
addEventListener('keyup',e=>keys.delete(e.code));canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'&&e.button===0&&mode==='play')fire=true;});addEventListener('pointerup',()=>fire=false);addEventListener('pointercancel',()=>fire=false);addEventListener('blur',()=>{keys.clear();fire=false;input?.clear();if(['play','victory','waveDefeat','intro'].includes(mode))pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&['play','victory','waveDefeat','intro'].includes(mode))pause();});
function finish(win){if(!['play'].includes(mode))return;mode=win?(waveIndex<level.enemyWaves.length-1?'waveDefeat':'victory'):'lost';document.body.dataset.mode=mode;victory=deathPulse=0;fire=false;keys.clear();clearStrikes();$('#hud').hidden=true;notice('');if(win){burst(boss.position.clone().add(new THREE.Vector3(0,4,0)),'#ffb56c',100,16);shake=.6;hitStop=.12;impact(boss.position,'#ffc491',160);tone(45,1);if(mode==='victory')result=campaign.reward(level.id,elapsed,hp/maxHp,runId);}else showResult(false);}
function showResult(win){document.body.classList.remove('is-paused');$('#footerlabel').textContent=win?'OPERATION COMPLETE':'FRAME LOST / RETRY AVAILABLE';$('#overlay').hidden=false;$('#overlabel').textContent=`MISSION 0${level.id} / ${level.title.toUpperCase()}`;$('#overtitle').textContent=win?(level.id===5?'THE ORBIT IS OURS.':'PLATFORM SECURED.'):'MISSION FAILED';$('#overtext').textContent=win?'All hostile frames neutralized. Choose your next deployment.':'Leave the strike markers before impact. Your earned scrap and upgrades are safe.';
 $('#result-summary').innerHTML=win&&result?`<div class="result-rating">${result.rating}</div><div class="result-metrics">SCORE ${result.score.toLocaleString()} · TIME ${formatTime(result.time)}<br>HULL ${Math.ceil(hp/maxHp*100)}% · <strong>+${result.reward} SCRAP</strong><br>${result.unlock==='pulse'?'UNLOCKED / PULSE REPEATER':result.unlock==='lance'?'UNLOCKED / ION LANCE':result.unlock==='modules'?'UNLOCKED / CORE MODULES':level.id===5?'CAMPAIGN COMPLETE · REPLAY FOR HIGHER RATINGS':'REWARDS SAVED'}</div>`:'';
 $('#resume').innerHTML=(win?'REPLAY MISSION':'RETRY MISSION')+' <span>↗</span>';$('#next-mission').hidden=!win||level.id===5;
}
function beginStrike(){strikeRadius=enemy.radius*(phase===2?1.2:1);const offsets=strikeOffsets(enemy.pattern,1);strikeCount=offsets.length;telegraph=enemy.warning*(phase===2?.8:1);offsets.forEach(([x,z],i)=>{strikePositions[i].set(THREE.MathUtils.clamp(hero.position.x+x*strikeRadius,-24,24),.02,THREE.MathUtils.clamp(hero.position.z+z*strikeRadius,-10,20));warningMarkers[i].position.copy(strikePositions[i]);warningMarkers[i].scale.setScalar(strikeRadius/4);warningMarkers[i].visible=true;});notice('INCOMING STRIKE / EVADE');tone(500,.2,'sine');}
function resolveStrike(){let hit=false;for(let i=0;i<strikeCount;i++){const p=strikePositions[i];burst(p,'#ff8b55',30,12);if(i===0){tracer(boss.position.clone().add(new THREE.Vector3(0,7,0)),p,amber);impact(p,'#ff9955',75);}if(hero.position.distanceTo(p)<strikeRadius&&dash<=.38)hit=true;}shake=.25;tone(50,.4);if(hit){hp=Math.max(0,hp-enemy.damage);document.body.classList.add('damage');setTimeout(()=>document.body.classList.remove('damage'),220);notice(hp/maxHp<.3?'HULL CRITICAL':'ARMOR HIT / REPOSITION');}clearStrikes();attackTimer=enemy.interval*(phase===2?.8:1);}
function updateHUD(){const integrity=Math.ceil(hp/maxHp*100);$('#hp').textContent=integrity;$('#hpbar').style.width=integrity+'%';$('#bossbar').style.width=Math.max(0,bhp/maxBhp*100)+'%';$('#heat').textContent=Math.round(heat)+'%';$('#heatbar').style.width=Math.min(100,heat)+'%';$('#cooldown').textContent=qcd>0?Math.ceil(qcd)+'s':'READY';}
let previousTime=performance.now(),t=0;
function update(){requestAnimationFrame(update);const now=performance.now(),realDt=Math.min((now-previousTime)/1000,.06);previousTime=now;let dt=mode==='pause'?0:realDt;if(hitStop>0){hitStop-=realDt;if(!settings.reducedMotion)dt*=.15;}t+=dt;
 const pad=input.poll(realDt);const particles=settings.particles==='high'?1800:700;rainGeo.setDrawRange(0,particles*2);
 if(dt>0){const rainSpeed=level.environmentTheme==='storm'&&mode!=='menu'?32:22;for(let i=0;i<particles*6;i+=6){rainPos[i]-=dt*2;rainPos[i+1]-=dt*rainSpeed;rainPos[i+3]-=dt*2;rainPos[i+4]-=dt*rainSpeed;if(rainPos[i+1]<0){rainPos[i+1]=50;rainPos[i+4]=50.7;}if(rainPos[i]<-50){rainPos[i]+=100;rainPos[i+3]+=100;}}rainGeo.attributes.position.needsUpdate=true;impacts.update(dt,camera);lightPool.update(dt);}
 shockAge+=dt;shock.visible=shockAge<1;shock.scale.setScalar(1+shockAge*16);shock.material.opacity=Math.max(0,1-shockAge)*.7;beamLife-=dt;beam.visible=beamLife>0;noticeT-=dt;if(noticeT<0)$('#notice').textContent='';
 if(mode==='menu'){const motion=settings.reducedMotion?0:1;hero.rotation.y=-.35+Math.sin(t*.17)*.08*motion;hero.position.y=Math.sin(t*1.4)*.025*motion;targetCam.set(10.5+Math.sin(t*.14)*.6*motion,5.1,15.5);look.set(innerWidth<800?-4.4:-2.3,2.65,3.4);boss.visible=false;steamTimer-=dt;if(steamTimer<0){steamTimer=1;impacts.emit(new THREE.Vector3(-5,.1,1),'#92c0cc',1,1.3);}}
 if(mode==='intro'){intro-=dt;targetCam.set(settings.reducedMotion?2.8:10,settings.reducedMotion?6.3:8,settings.reducedMotion?17:8);look.set(0,4,-12);if(intro<=0){mode='play';document.body.dataset.mode='play';notice('TARGET LOCKED / '+enemy.name);}}
 if(mode==='play'){
  elapsed+=realDt;shot-=dt;dash-=dt;qcd=Math.max(0,qcd-dt);heat=Math.max(0,heat-dt*moduleStats.cooling);if(overheat&&heat<28){overheat=false;notice('THERMAL SYSTEM RESTORED');}
  const dx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+pad.dx,dz=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0)+pad.dz,moving=Math.abs(dx)+Math.abs(dz)>.1;const speed=dash>.38?24:moduleStats.speed;
  if(moving){const len=Math.max(1,Math.hypot(dx,dz));hero.position.x=THREE.MathUtils.clamp(hero.position.x+dx/len*dt*speed,-23,23);hero.position.z=THREE.MathUtils.clamp(hero.position.z+dz/len*dt*speed,-9,19);walk+=dt*9;}
  hero.position.y=settings.reducedMotion?0:moving?Math.abs(Math.sin(walk))*.09:Math.sin(t*2)*.02;hero.userData.legs.forEach((l,i)=>l.rotation.x=THREE.MathUtils.damp(l.rotation.x,moving?Math.sin(walk+i*Math.PI)*.34:0,12,dt));hero.rotation.y=Math.atan2(boss.position.x-hero.position.x,boss.position.z-hero.position.z);
  enemyPoint.copy(boss.position);enemyPoint.y+=enemy.scale*3.3;aimPoint.copy(enemyPoint).project(camera);const assisted=settings.controlMode==='assisted';const aimDistance=Math.hypot(input.aim.x-aimPoint.x,input.aim.y-aimPoint.y);const onTarget=assisted||aimDistance<(settings.aimAssist?.26:.13);const reticle=$('#reticle');reticle.style.left=(assisted?THREE.MathUtils.clamp((aimPoint.x+1)*50,8,92):(input.aim.x+1)*50)+'%';reticle.style.top=(assisted?THREE.MathUtils.clamp((1-aimPoint.y)*50,15,80):(1-input.aim.y)*50)+'%';reticle.style.color=onTarget?'#b1eee1':'#e1a486';$('#reticle small').textContent=onTarget?'TARGET LINKED':'MANUAL AIM';
  if((fire||keys.has('KeyF')||pad.fire)&&shot<=0&&!overheat){shot=weapon.interval;heat+=weapon.heat;if(onTarget)bhp=Math.max(0,bhp-weapon.damage*(phase===1?.72:1));shake=.05;hero.updateMatrixWorld(true);muzzlePoint.set(1.47,2.03,3).applyMatrix4(hero.matrixWorld);let endpoint=enemyPoint.clone();if(!onTarget)endpoint.set(input.aim.x,input.aim.y,.8).unproject(camera).sub(camera.position).normalize().multiplyScalar(60).add(camera.position);tracer(muzzlePoint,endpoint,cyan);lightPool.emit(muzzlePoint,weapon.color,16,.09,camera);if(onTarget)burst(endpoint,weapon.color,8,5);tone(campaign.save.equipped==='lance'?90:180,.09,'sawtooth',.016);hero.userData.gun.position.z=.45;if(heat>=95){overheat=true;notice('HEAT CRITICAL / VENTING');}}
  hero.userData.gun.position.z=THREE.MathUtils.damp(hero.userData.gun.position.z,.6,14,dt);
  if(bhp<maxBhp*.5&&phase===1){phase=2;notice('ARMOR BREACH / CORE EXPOSED');$('#phase').textContent='02 / UNBOUND';hitStop=.08;impact(boss.position,'#ff615c',90);boss.userData.arms.forEach(a=>a.rotation.z=a.position.x>0?-.22:.22);burst(enemyPoint,'#ffb37e',45,10);shake=.3;}
  boss.position.x=Math.sin(elapsed*(.25+level.id*.045))*(3+level.id*.4);boss.rotation.y=Math.atan2(hero.position.x-boss.position.x,hero.position.z-boss.position.z);boss.userData.arms.forEach((a,i)=>a.rotation.x=Math.sin(t*1.5+i)*.12);
  attackTimer-=dt;if(attackTimer<=0&&telegraph<=0)beginStrike();if(telegraph>0){telegraph-=dt;warning.material.opacity=settings.reducedMotion?.65:.55+Math.sin(t*12)*.2;if(telegraph<=0)resolveStrike();}
  if(bhp<=0)finish(true);else if(hp<=0)finish(false);targetCam.set(hero.position.x+2.8,6.3,hero.position.z+10);look.set(hero.position.x*.35,3.3,hero.position.z-11);
 }
 if(mode==='victory'||mode==='waveDefeat'){
  victory+=dt;deathPulse-=dt;purple.emissiveIntensity=Math.max(.08,1.8-victory*.4);boss.rotation.z=THREE.MathUtils.damp(boss.rotation.z,.85,1.2,dt);boss.position.y=THREE.MathUtils.damp(boss.position.y,-1.3,1,dt);
  if(deathPulse<=0&&victory<3){deathPulse=.4;const p=boss.position.clone().add(new THREE.Vector3((rand()-.5)*5,2+rand()*5,rand()*2));burst(p,'#ffbb80',30,9);lightPool.emit(p,'#ff984f',85,.3,camera,3);shake=.2;}
  if(!settings.reducedMotion){targetCam.set(hero.position.x+Math.sin(victory*.25)*10,5,hero.position.z+Math.cos(victory*.25)*10);look.copy(hero.position).add(new THREE.Vector3(0,2.5,0));}
  if(victory>3.6){if(mode==='waveDefeat'){waveIndex++;hp=Math.min(maxHp,hp+15);heat=0;spawnEnemy();mode='intro';intro=2;$('#hud').hidden=false;notice('FIELD REPAIR +15 / NEXT HOSTILE');}else{mode='complete';showResult(true);}document.body.dataset.mode=mode;}
 }
 if(mode!=='pause'){camera.position.lerp(targetCam,1-Math.exp(-dt*2.8));camera.lookAt(look);shake=Math.max(0,shake-dt);if(settings.shake&&!settings.reducedMotion){camera.position.x+=(rand()-.5)*shake;camera.position.y+=(rand()-.5)*shake;}}
 uiTimer-=realDt;if(uiTimer<=0){updateHUD();uiTimer=.08;}if(hangarPreview){camera.position.copy(hero.position).add(new THREE.Vector3(9,4.5,11));camera.lookAt(hero.position.x-3,hero.position.y+2.5,hero.position.z);}
 composer.render();
}
const quality=document.createElement('button');quality.id='quality';document.querySelector('header').append(quality);
function applyOptions(o){settings={...o};const ratio=Math.min(devicePixelRatio,o.quality==='high'?(innerWidth<800?1.25:1.5):1);if(renderer.getPixelRatio()!==ratio){renderer.setPixelRatio(ratio);composer.setPixelRatio(ratio);}const shadowSize=o.shadows==='high'?2048:1024;if(key.shadow.mapSize.x!==shadowSize){key.shadow.mapSize.setScalar(shadowSize);key.shadow.dispose();key.shadow.map=null;key.shadow.mapPass=null;}renderer.shadowMap.enabled=o.shadows!=='off';key.shadow.needsUpdate=true;bloomPass.enabled=o.bloom;document.body.classList.toggle('reduced-motion',o.reducedMotion);$('#sound').textContent=o.mute?'SOUND OFF':'SOUND ON';quality.textContent='QUALITY '+o.quality.toUpperCase();}
$('#sound').onclick=()=>{activateAudio();campaign.option('mute',!settings.mute);};quality.onclick=()=>campaign.option('quality',settings.quality==='high'?'medium':'high');$('#pause').onclick=pause;$('#resume').onclick=()=>mode==='pause'?pause():campaign.briefing(level.id);$('#next-mission').onclick=()=>campaign.briefing(Math.min(5,level.id+1));$('#help').onclick=openGuide;$('#close-help').onclick=closeGuide;$('#guide-done').onclick=closeGuide;$('#guide').addEventListener('cancel',e=>{e.preventDefault();closeGuide();});
campaign=mountCampaign({load:loadMission,launch:start,title:returnTitle,options:applyOptions,suspend,controls:openGuide,previewLoadout,preview:active=>hangarPreview=active,inCombat:()=>['play','intro','victory','waveDefeat','pause'].includes(mode)});
input=createInput({canvas,options:()=>settings,active:()=>mode==='play',onAction:action});returnTitle();update();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);applyOptions(settings);});
